### YamlMime:Lifecycle
metadata:
  title: „Microsoft System Center 2012 R2 Configuration Manager“
  description: „Microsoft System Center 2012 R2 Configuration Manager“ atitinka fiksuotojo ciklo palaikymo strategiją.
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: 77ccf20600724e3655e7705df6450819ea5f6ceb
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: lt-LT
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4152859"
name: „Microsoft System Center 2012 R2 Configuration Manager“
summary: >+
  „Microsoft System Center 2012 R2 Configuration Manager“ atitinka [fiksuotojo](/lifecycle/policies/fixed) ciklo palaikymo strategiją.


products:
- msc
policyType: fixed
supportDates:
  start: 2014-01-16T00:00:00.000-08:00
  end: 2017-07-11T22:59:59.999-08:00
  extendedEnd: 2022-07-12T22:59:59.999-08:00
releases:
- version: Service Pack 1
  startDate: 2015-05-12T00:00:00.000-08:00
  endDate: 2022-07-12T22:59:59.999-08:00
- version: Original Release
  startDate: 2014-01-16T00:00:00.000-08:00
  endDate: 2016-07-12T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Saitai \n* [Pakeitimų paketo strategija](/lifecycle/policies/fixed#service-packs)\n* [Konfigūracijos tvarkytuvo dokumentai](/mem/configmgr/core/misc/online-documentation)\n* [Perkėlimo našumo rekomendacijos](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
