### YamlMime:Lifecycle
metadata:
  title: „Microsoft Application Virtualization Hosting 4.5“, skirtas staliniams kompiuteriams
  description: „Microsoft Application Virtualization Hosting 4.5“, skirta „Windows“ staliniams kompiuteriams, atitinka fiksuotąją ciklo palaikymo strategiją.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 2e50dff8c1e7f1db82d46a06704bad1c76d16598
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: lt-LT
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4154043"
name: „Microsoft Application Virtualization Hosting 4.5“, skirtas staliniams kompiuteriams
summary: "„Microsoft Application Virtualization Hosting 4.5“, skirta „Windows“ staliniams kompiuteriams, atitinka [fiksuotąją](/lifecycle/policies/fixed) ciklo palaikymo strategiją. \n\nTai taikoma šiems leidimams: „Windows“ staliniams kompiuteriams\n\n> [!IMPORTANT]\n> Baigėsi šio produkto palaikymas. Žiūrėkite toliau pateiktą perkėlimo informaciją.\n"
products:
- windows
policyType: fixed
supportDates:
  start: 2008-11-23T00:00:00.000-08:00
  end: 2014-01-14T22:59:59.999-08:00
  extendedEnd: 2019-01-08T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2010-08-15T00:00:00.000-08:00
  endDate: 2019-01-08T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2009-12-13T00:00:00.000-08:00
  endDate: 2011-10-11T22:59:59.999-08:00
- version: Original Release
  startDate: 2008-11-23T00:00:00.000-08:00
  endDate: 2011-01-11T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Saitai \n* [Produkto ir perkėlimo informacija](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Pakeitimų paketo strategija](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Leidimai \n* „Windows“ staliniams kompiuteriams"
