### YamlMime:Lifecycle
metadata:
  title: '„Microsoft Application Virtualization Hosting 5.1“, skirtas staliniams kompiuteriams'
  description: '„Microsoft Application Virtualization Hosting 5.1“, skirta „Windows“ staliniams kompiuteriams, atitinka fiksuotojo ciklo palaikymo strategiją.'
  ms.date: 09/10/2020
  keywords: for Windows Desktops
name: '„Microsoft Application Virtualization Hosting 5.1“, skirtas staliniams kompiuteriams'
summary: |+
  „Microsoft Application Virtualization Hosting 5.1“, skirta „Windows“ staliniams kompiuteriams, atitinka [fiksuotojo](/lifecycle/policies/fixed) ciklo palaikymo strategiją.

  Tai taikoma šiems leidimams: „Windows“ staliniams kompiuteriams

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Original Release
    startDate: 11/01/2015
    endDate: 04/14/2026
content: |

  ## <a name="links"></a>Saitai 
  * [Informacija apie gaminį](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)


  ## <a name="editions"></a>Leidimai 
  * „Windows“ staliniams kompiuteriams