### YamlMime:Lifecycle
metadata:
  title: Microsoft visuotinio diegimo agentas 2013
  description: "\"Microsoft\" diegimo agentas 2013 po fiksuoto palaikymo trukmės strategija."
  ms.date: 07/28/2020
  ms.openlocfilehash: d81680178f3fc6d72450bbf62cbf11ccb7ef8dc5
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: lt-LT
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "858901"
name: Microsoft visuotinio diegimo agentas 2013
summary: "\"Microsoft\" diegimo agentas 2013 po [fiksuoto](/lifecycle/policies/fixed) palaikymo trukmės strategija.\n\n\n"
products:
- vs
policyType: fixed
supportDates:
  start: 01/15/2014
  end: 04/09/2019
  extendedEnd: 04/09/2024
releases:
- version: Original Release
  startDate: 01/15/2014
  endDate: 04/09/2024
content: "\n\n> [!NOTE]\n> Visuotinio diegimo agentas 2013, 4 naujinimas bus palaikomas pagal strategijos gaires iki 4/9/2024."
