### YamlMime:Lifecycle
metadata:
  title: "\"Microsoft Forefront Client Security\""
  description: "\"Microsoft Forefront Client Security\" vadovaujasi nustatyta gyvavimo ciklo strategija."
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: lt-LT
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924264"
name: "\"Microsoft Forefront Client Security\""
summary: "\"Microsoft Forefront Client Security\" vadovaujasi [nustatyta](/lifecycle/policies/fixed) gyvavimo ciklo strategija.\n\n\n"
products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Saitai \n* [Sistemos centro galinio punkto apsauga](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> \"Forefront Client Security\" buvo nutraukta nuo liepos 14 d., 2015. Apsaugos nuo kenkėjiškų programų ir kenkėjiškų programų aprašų naujinimų nebebus galima po produkto versijos palaikymo pabaigos. Vertinkite sistemos centro galinio punkto apsaugą kaip pakeitimą."
