### YamlMime:Lifecycle
metadata:
  title: „Microsoft System Center Configuration Manager 2007 R3“
  description: „Microsoft System Center Configuration Manager 2007 R3“ atitinka fiksuotojo ciklo palaikymo strategiją.
  ms.date: 07/28/2020
name: „Microsoft System Center Configuration Manager 2007 R3“
summary: |
  „Microsoft System Center Configuration Manager 2007 R3“ atitinka [fiksuotojo](/lifecycle/policies/fixed) ciklo palaikymo strategiją.


  > [!IMPORTANT]
  > Baigėsi šio produkto palaikymas. Žiūrėkite toliau pateiktas perkėlimo gaires.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Saitai 
  * [Perkėlimo našumo rekomendacijos](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Papildomos perkėlimo gairės](/mem/configmgr/core/migration/planning-for-migration)