### YamlMime:Lifecycle
metadata:
  title: Microsoft taikomosios programos virtualizavimo 5,1
  description: "\"Microsoft\" taikomosios programos virtualizavimo 5.1 taip fiksuoto palaikymo trukmės strategija."
  ms.date: 07/28/2020
  ms.openlocfilehash: 3f0cac2ee013dd73e44fe41d9ba1d07cfcfce2f1
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: lt-LT
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "858910"
name: Microsoft taikomosios programos virtualizavimo 5,1
summary: "\"Microsoft\" taikomosios programos virtualizavimo 5.1 taip [fiksuoto](/lifecycle/policies/fixed) palaikymo trukmės strategija.\n\nTai taikoma šiems leidimams: nuotolinio darbalaukio tarnyboms, \"Windows\" darbalaukiams\n\n"
products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Nuorodos \n* [Informacija apie gaminį](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Leidimai \n* nuotolinio darbalaukio tarnyboms\n* skirta \"Windows\" staliniams kompiuteriams"
