### YamlMime:Lifecycle
metadata:
  title: „Microsoft System Center Configuration Manager 2007 R3“
  description: „Microsoft System Center Configuration Manager 2007 R3“ atitinka fiksuotojo ciklo palaikymo strategiją.
  ms.date: 07/28/2020
  ms.openlocfilehash: 1066e1999c057459643c64aba46bb88e34bb4842
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: lt-LT
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4137430"
name: „Microsoft System Center Configuration Manager 2007 R3“
summary: >
  „Microsoft System Center Configuration Manager 2007 R3“ atitinka [fiksuotojo](/lifecycle/policies/fixed) ciklo palaikymo strategiją.



  > [!IMPORTANT]

  > Baigėsi šio produkto palaikymas. Žiūrėkite toliau pateiktas perkėlimo gaires.
products:
- msc
policyType: fixed
supportDates:
  start: 2010-12-19T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2010-12-19T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Saitai \n* [Perkėlimo našumo rekomendacijos](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Papildomos perkėlimo gairės](/mem/configmgr/core/migration/planning-for-migration)"
