### YamlMime:Lifecycle
metadata:
  title: „Microsoft Application Virtualization Hosting 5.1“, skirtas staliniams kompiuteriams
  description: „Microsoft Application Virtualization Hosting 5.1“, skirta „Windows“ staliniams kompiuteriams, atitinka fiksuotąją ciklo palaikymo strategiją.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 9296a136a0bc0da5a6d6b6b8b49d012170158da0
  ms.sourcegitcommit: c0c65f657b1da8e588fda5bedd3572fb2e3168bc
  ms.translationtype: HT
  ms.contentlocale: lt-LT
  ms.lasthandoff: 09/10/2020
  ms.locfileid: "1000584"
name: „Microsoft Application Virtualization Hosting 5.1“, skirtas staliniams kompiuteriams
summary: >+
  „Microsoft Application Virtualization Hosting 5.1“, skirta „Windows“ staliniams kompiuteriams, atitinka [fiksuotąją](/lifecycle/policies/fixed) ciklo palaikymo strategiją.


  Tai taikoma šiems leidimams: „Windows“ staliniams kompiuteriams

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Saitai \n* [Informacija apie gaminį](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Leidimai \n* „Windows“ staliniams kompiuteriams"
