### YamlMime:Lifecycle
metadata:
  title: SoftGrid taikomosios programos virtualizavimas
  description: SoftGrid programos virtualizavimas po fiksuoto palaikymo trukmės strategija.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: lt-LT
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "829066"
name: SoftGrid taikomosios programos virtualizavimas
summary: >
  SoftGrid programos virtualizavimas po [fiksuoto](/lifecycle/policies/fixed) palaikymo trukmės strategija.


  Tai taikoma šiems leidimams: 4.1 staliniams kompiuteriams, 4.2 staliniams kompiuteriams, terminalų tarnyboms 4.1


  > [!IMPORTANT]

  > Palaikymas baigėsi. Žiūrėkite toliau pateiktas išsiskyrimo gaires.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Nuorodos \n* [Migracijos gairės](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Leidimai \n* 4.1 staliniams kompiuteriams\n* 4.2 staliniams kompiuteriams\n* terminalų paslaugų 4,1"
